# Generated by Django 5.2.5 on 2025-11-14 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proyectos", "0002_rol"),
    ]

    operations = [
        migrations.AddField(
            model_name="proyecto",
            name="complejidad",
            field=models.CharField(
                choices=[("baja", "Baja"), ("media", "Media"), ("alta", "Alta")],
                default="media",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="proyecto",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("construccion", "Construcción"),
                    ("mantenimiento", "Mantenimiento"),
                    ("instalacion", "Instalación"),
                    ("otro", "Otro"),
                ],
                default="otro",
                max_length=30,
            ),
        ),
    ]
