# Generated by Django 5.2.5 on 2025-11-12 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("personal", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trabajador",
            name="cuadrilla",
        ),
        migrations.RemoveField(
            model_name="trabajador",
            name="usuario",
        ),
        migrations.DeleteModel(
            name="Cuadrilla",
        ),
        migrations.DeleteModel(
            name="Trabajador",
        ),
    ]
