# Generated by Django 5.2.5 on 2025-11-14 01:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("personal", "0004_rol_remove_cuadrilla_activa_alter_cuadrilla_lider_and_more"),
        ("proyectos", "0002_rol"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Certificacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("archivo", models.FileField(upload_to="certificaciones/")),
                ("fecha_emision", models.DateField()),
                ("fecha_expiracion", models.DateField(blank=True, null=True)),
                ("entidad", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "trabajador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificaciones",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Competencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("descripcion", models.TextField(blank=True, null=True)),
                ("certificada", models.BooleanField(default=False)),
                (
                    "trabajador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="competencias",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Experiencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "proyecto_externo",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                (
                    "empresa_externa",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                (
                    "meses_participacion",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "calificacion",
                    models.CharField(
                        choices=[
                            ("no_recomendado", "No recomendado"),
                            ("recomendado", "Recomendado"),
                            ("muy_recomendado", "Muy recomendado"),
                        ],
                        max_length=20,
                    ),
                ),
                ("descripcion", models.TextField(blank=True, null=True)),
                (
                    "proyecto",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="experiencias_trabajador",
                        to="proyectos.proyecto",
                    ),
                ),
                (
                    "trabajador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="experiencias",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TrabajadorPerfil",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "especialidad",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "estado_manual",
                    models.CharField(
                        choices=[
                            ("disponible", "Disponible"),
                            ("no_disponible", "No disponible"),
                            ("licencia", "Licencia médica"),
                            ("vacaciones", "Vacaciones"),
                        ],
                        default="disponible",
                        max_length=20,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="perfil_trabajador",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
