# Generated by Django 5.2.5 on 2025-11-14 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("personal", "0005_certificacion_competencia_experiencia_and_more"),
        ("proyectos", "0002_rol"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cuadrilla",
            name="proyecto",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cuadrillas",
                to="proyectos.proyecto",
            ),
        ),
    ]
