# Generated by Django 5.2.5 on 2025-11-14 14:38

import django.db.models.deletion
import personal.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("personal", "0006_alter_cuadrilla_proyecto"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Trabajador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rut",
                    models.CharField(
                        max_length=20,
                        unique=True,
                        validators=[personal.models.rut_valido],
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("apellido", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("telefono", models.CharField(blank=True, max_length=30, null=True)),
                ("direccion", models.CharField(blank=True, max_length=255, null=True)),
                ("fecha_nacimiento", models.DateField(blank=True, null=True)),
                (
                    "tipo_trabajador",
                    models.CharField(
                        choices=[
                            ("trabajador", "Trabajador"),
                            ("lider", "Líder"),
                            ("jefe", "Jefe"),
                        ],
                        default="trabajador",
                        max_length=20,
                    ),
                ),
                (
                    "especialidad",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("disponible", "Disponible"),
                            ("asignado", "Asignado"),
                            ("vacaciones", "Vacaciones"),
                            ("licencia", "Licencia"),
                            ("inactivo", "Inactivo"),
                        ],
                        default="disponible",
                        max_length=20,
                    ),
                ),
                ("fecha_ingreso", models.DateField(blank=True, null=True)),
                ("anos_experiencia", models.PositiveIntegerField(default=0)),
                ("activo", models.BooleanField(default=True)),
                ("password_inicial", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="trabajador_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Trabajador",
                "verbose_name_plural": "Trabajadores",
            },
        ),
        migrations.CreateModel(
            name="ExperienciaTrabajador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("proyecto", models.CharField(blank=True, max_length=150, null=True)),
                (
                    "empresa_externa",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("rol", models.CharField(blank=True, max_length=100, null=True)),
                ("fecha_inicio", models.DateField(blank=True, null=True)),
                ("fecha_termino", models.DateField(blank=True, null=True)),
                (
                    "calificacion",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("no_recomendado", "No recomendado"),
                            ("recomendado", "Recomendado"),
                            ("muy_recomendado", "Muy recomendado"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "trabajador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="experiencias_trabajador",
                        to="personal.trabajador",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CertificacionTrabajador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=150)),
                ("entidad", models.CharField(blank=True, max_length=150, null=True)),
                (
                    "archivo",
                    models.FileField(
                        blank=True, null=True, upload_to="certificaciones/"
                    ),
                ),
                ("fecha_emision", models.DateField()),
                ("fecha_expiracion", models.DateField(blank=True, null=True)),
                (
                    "trabajador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificaciones_trabajador",
                        to="personal.trabajador",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CompetenciaTrabajador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                (
                    "nivel",
                    models.CharField(
                        choices=[
                            ("basico", "Básico"),
                            ("intermedio", "Intermedio"),
                            ("avanzado", "Avanzado"),
                            ("experto", "Experto"),
                        ],
                        default="basico",
                        max_length=20,
                    ),
                ),
                ("fecha_adquisicion", models.DateField(blank=True, null=True)),
                (
                    "trabajador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="competencias",
                        to="personal.trabajador",
                    ),
                ),
            ],
            options={
                "unique_together": {("trabajador", "nombre")},
            },
        ),
    ]
