# Generated by Django 5.2.5 on 2025-11-20 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("personal", "0008_notificacion"),
    ]

    operations = [
        migrations.AddField(
            model_name="trabajador",
            name="manual_override",
            field=models.BooleanField(default=False),
        ),
    ]
