# Generated by Django 5.2.5 on 2025-11-13 00:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("personal", "0003_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Recurso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("tipo", models.CharField(max_length=50)),
                ("cantidad", models.PositiveIntegerField()),
                ("unidad", models.CharField(default="unidades", max_length=20)),
                (
                    "cuadrilla",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recursos",
                        to="personal.cuadrilla",
                    ),
                ),
            ],
        ),
    ]
