# Generated by Django 5.2.5 on 2025-11-27 16:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comunicacion", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="archived",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="ChatArchivado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("archived_at", models.DateTimeField()),
                ("reason", models.CharField(blank=True, max_length=200, null=True)),
                ("messages_snapshot", models.TextField()),
                (
                    "archived_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="archivos_chat",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "conversation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="archivos",
                        to="comunicacion.conversation",
                    ),
                ),
            ],
            options={
                "ordering": ["-archived_at"],
            },
        ),
    ]
