# Generated by Django 5.2.5 on 2025-11-27 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comunicacion", "0002_conversation_archived_chatarchivado"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatarchivado",
            name="participants_snapshot",
            field=models.TextField(blank=True, null=True),
        ),
    ]
